# Generated by Django 4.0.4 on 2022-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnoApp', '0002_rename_search_word_new_model_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_model',
            name='Content',
            field=models.TextField(max_length=300000),
        ),
    ]
