# Generated by Django 4.0.4 on 2022-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnoApp', '0003_alter_new_model_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback1', models.CharField(max_length=20)),
                ('feedback2', models.CharField(max_length=20)),
            ],
        ),
    ]
